[difficutlies]
    [easy]
        width = 9
        height = 9
        bombs = 15
    [easy]
        width = 9
        height = 9
        bombs = 30
    [hard]
        width = 9
        height = 9
        bombs = 50

[settings]
    savePath = ""
    language = "en-US"
